version: '3.8'
services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=kirillbatutin
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres

  telegrambot:
    container_name: telegrambot
    image: telegrambot:0.0.1
    build:
      context: ./telegrambot
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    - SPRING_DATASOURCE_USERNAME=kirillbatutin
    - SPRING_DATASOURCE_PASSWORD=
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    depends_on:
    - db

  currencyRateParser:
    container_name: currencyRateParser
    image: currency:0.0.1
    build:
      context: ./currencyRateParser
      dockerfile: Dockerfile
    ports:
      - 8282:8282
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=kirillbatutin
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    depends_on:
      - db
      - telegrambot