version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=kirillbatutin
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
    networks:
      - my_network

  telegrambot:
    container_name: telegrambot
    image: telegrambot:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
      - "5006:5006"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=kirillbatutin
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - my_network
#
#  currencyRateParser:
#    container_name: currencyRateParser
#    image: currency:0.0.1
#    build:
#      context: ./currencyRateParser
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=kirillbatutin
#      - SPRING_DATASOURCE_PASSWORD=
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    depends_on:
#      - db
#      - telegrambot
#    networks:
#      - my_network

networks:
  my_network:
    external: true